version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: healthgoal-postgres
    environment:
      POSTGRES_DB: healthgoal
      POSTGRES_USER: healthgoal_user
      POSTGRES_PASSWORD: healthgoal_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U healthgoal_user -d healthgoal"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthgoal-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/healthgoal
      SPRING_DATASOURCE_USERNAME: healthgoal_user
      SPRING_DATASOURCE_PASSWORD: healthgoal_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    entrypoint: ["sh", "/app/entrypoint.sh"]

volumes:
  postgres_data:
